### ISSUE TITLE
OS and AirSim Versions

### ISSUE THREAD

**Issue by ajberlier** [Mayankm96/airsim_ros_client#8]
What version of OS and AirSim have you tested with? Thank you for the help!

**Comment by Mayankm96** [comment]
It has been a while since I have updated the code in this repository. I was using it on Ubuntu 16.04LTS with ROS Kinetic. 

The AirSim commit at that point of time should be this one: https://github.com/Mayankm96/AirSim_ROS

**Comment by pengzhi1998** [comment]
Hi @Mayankm96 , thank you for this great work!
However, which python version are you using? I remember that ROS is suitable only for Python 2. However, AirSim requires Python 3. How to deal with that? Thank you for your help!!
